<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <link rel="icon" href="../favicon.ico" />
  <link rel="stylesheet" href="../style.css">
  <title>PG::ConnectionBad - サーバーに接続できませんでした: 接続が拒否されました | Techioz</title>
  <style type="text/css">code{white-space: pre;}</style>
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1637770322917058"
     crossorigin="anonymous"></script>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-DRM1ZRNLDN"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-DRM1ZRNLDN');
  </script>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Article",
  "headline": "PG::ConnectionBad - サーバーに接続できませんでした: 接続が拒否されました",
  "author": {
    "@type": "Person",
    "address": "",
    "email": null,
    "identifier": "masyumaroking",
    "name": "masyumaroking"
  },
  "publisher": {
    "@type": "Person",
    "name": "masyumaroking"
  }
}
</script>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
  <header>
    <div class="container">
        <h1>Techioz Blog</h1>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Articles</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
    </div>
  </header>
  <main>
    <div class="container">
        <article>
                      <h2>PG::ConnectionBad -
サーバーに接続できませんでした: 接続が拒否されました</h2>
                    <h2 id="概要">概要</h2>
                    <p>Rails 4.0
                    サーバーを実行するたびに、この出力が表示されます。</p>
                    <pre><code>Started GET &quot;/&quot; for 127.0.0.1 at 2013-11-06 23:56:36 -0500

PG::ConnectionBad - could not connect to server: Connection refused
Is the server running on host &quot;localhost&quot; (::1) and accepting
TCP/IP connections on port 5432?
could not connect to server: Connection refused
Is the server running on host &quot;localhost&quot; (127.0.0.1) and accepting
TCP/IP connections on port 5432?
could not connect to server: Connection refused
Is the server running on host &quot;localhost&quot; (fe80::1) and accepting
TCP/IP connections on port 5432?
:
 activerecord (4.0.0) lib/active_record/connection_adapters/postgresql_adapter.rb:825:in `connect&#39;
 activerecord (4.0.0) lib/active_record/connection_adapters/postgresql_adapter.rb:542:in `initialize&#39;
 activerecord (4.0.0) lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `postgresql_connection&#39;
 activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:440:in `new_connection&#39;
 activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:450:in `checkout_new_connection&#39;
 activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:421:in `acquire_connection&#39;
 activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:356:in `block in checkout&#39;
 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize&#39;
 activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:355:in `checkout&#39;
 activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection&#39;
 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize&#39;
 activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection&#39;
 activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:546:in `retrieve_connection&#39;
 activerecord (4.0.0) lib/active_record/connection_handling.rb:79:in `retrieve_connection&#39;
 activerecord (4.0.0) lib/active_record/connection_handling.rb:53:in `connection&#39;
 activerecord (4.0.0) lib/active_record/migration.rb:792:in `current_version&#39;
 activerecord (4.0.0) lib/active_record/migration.rb:800:in `needs_migration?&#39;
 activerecord (4.0.0) lib/active_record/migration.rb:379:in `check_pending!&#39;
 activerecord (4.0.0) lib/active_record/migration.rb:366:in `call&#39;
 actionpack (4.0.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call&#39;
 activesupport (4.0.0) lib/active_support/callbacks.rb:373:in `_run__1613334440513032208__call__callbacks&#39;
 activesupport (4.0.0) lib/active_support/callbacks.rb:80:in `run_callbacks&#39;
 actionpack (4.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call&#39;
 actionpack (4.0.0) lib/action_dispatch/middleware/reloader.rb:64:in `call&#39;
 actionpack (4.0.0) lib/action_dispatch/middleware/remote_ip.rb:76:in `call&#39;
 better_errors (0.9.0) lib/better_errors/middleware.rb:84:in `protected_app_call&#39;
 better_errors (0.9.0) lib/better_errors/middleware.rb:79:in `better_errors_call&#39;
 better_errors (0.9.0) lib/better_errors/middleware.rb:56:in `call&#39;
 actionpack (4.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call&#39;
 actionpack (4.0.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call&#39;
 railties (4.0.0) lib/rails/rack/logger.rb:38:in `call_app&#39;
 railties (4.0.0) lib/rails/rack/logger.rb:21:in `block in call&#39;
 activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `block in tagged&#39;
 activesupport (4.0.0) lib/active_support/tagged_logging.rb:25:in `tagged&#39;
 activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `tagged&#39;
 railties (4.0.0) lib/rails/rack/logger.rb:21:in `call&#39;
 quiet_assets (1.0.2) lib/quiet_assets.rb:18:in `call_with_quiet_assets&#39;
 actionpack (4.0.0) lib/action_dispatch/middleware/request_id.rb:21:in `call&#39;
 rack (1.5.2) lib/rack/methodoverride.rb:21:in `call&#39;
 rack (1.5.2) lib/rack/runtime.rb:17:in `call&#39;
 activesupport (4.0.0) lib/active_support/cache/strategy/local_cache.rb:83:in `call&#39;
 rack (1.5.2) lib/rack/lock.rb:17:in `call&#39;
 actionpack (4.0.0) lib/action_dispatch/middleware/static.rb:64:in `call&#39;
 railties (4.0.0) lib/rails/engine.rb:511:in `call&#39;
 railties (4.0.0) lib/rails/application.rb:97:in `call&#39;
 rack (1.5.2) lib/rack/content_length.rb:14:in `call&#39;
 thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process&#39;
 thin (1.5.1) lib/thin/connection.rb:79:in `pre_process&#39;
 thin (1.5.1) lib/thin/connection.rb:54:in `process&#39;
 thin (1.5.1) lib/thin/connection.rb:39:in `receive_data&#39;
 eventmachine (1.0.3) lib/eventmachine.rb:187:in `run&#39;
 thin (1.5.1) lib/thin/backends/base.rb:63:in `start&#39;
 thin (1.5.1) lib/thin/server.rb:159:in `start&#39;
 rack (1.5.2) lib/rack/handler/thin.rb:16:in `run&#39;
 rack (1.5.2) lib/rack/server.rb:264:in `start&#39;
 railties (4.0.0) lib/rails/commands/server.rb:84:in `start&#39;
 railties (4.0.0) lib/rails/commands.rb:78:in `block in &lt;top (required)&gt;&#39;
 railties (4.0.0) lib/rails/commands.rb:73:in `&lt;top (required)&gt;&#39;
 bin/rails:4:in `&lt;main&gt;&#39;
</code></pre>
                    <p>私は Mavericks OS X 10.9
                    を実行しているので、それが問題かどうかはわかりません。できることはすべて試しましたが、何もうまくいかないようです。
                    postgres と pg gem
                    の両方を何度もアンインストールしてインストールしました。</p>
                    <p>これは私のdatabase.ymlファイルです</p>
                    <pre><code>development:
  adapter: postgresql
  encoding: unicode
  database: metals-directory_development
  pool: 5
  username: 
  password: 
  template: template0
  host: localhost
  port: 5432

test: &amp;test
  adapter: postgresql
  encoding: unicode
  database: metals-directory_test
  pool: 5
  username: 
  password: 
  template: template0
  host: localhost
  port: 5432

staging:
  adapter: postgresql
  encoding: unicode
  database: metals-directory_production
  pool: 5
  username:
  password:
  template: template0
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: metals-directory_production
  pool: 5
  username:
  password:
  template: template0
  host: localhost

cucumber:
  &lt;&lt;: *test
</code></pre>
                    <h2 id="解決策">解決策</h2>
                    <p>古い PID
                    ファイルと同じくらい単純な場合もあります。コンピューターがシャットダウンプロセスを完全に完了していないため、サイレントに失敗している可能性があります。これは、postgres
                    が PID (プロセス ID)
                    ファイルを削除していないことを意味します。</p>
                    <p>PID ファイルは、サーバーのインスタンスが一度に 1
                    つだけ実行されるようにするために postgres
                    によって使用されます。したがって、再度起動しようとすると、サーバーの別のインスタンスが起動されたことをpostgresに伝えるPIDファイルがすでに存在するため、失敗します(たとえ実行されていないとしても、シャットダウンしてPIDを削除できなかっただけです)。
                    。</p>
                    <p>または、古いバージョンの Brew の場合</p>
                    <pre><code>    launchctl unload homebrew.mxcl.postgresql.plist  
    launchctl load -w homebrew.mxcl.postgresql.plist
</code></pre>
        </article>
    </div>
  </main>
  <footer>
    <div class="container">
        <p>&copy; 2024 Techioz. All rights reserved.</p>
    </div>
  </footer>
</body>
</html>