<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <link rel="icon" href="../favicon.ico" />
  <link rel="stylesheet" href="../style.css">
  <title>Ruby でのシステムコール上のネストされたタイムアウトの問題 | Techioz</title>
  <style type="text/css">code{white-space: pre;}</style>
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1637770322917058"
     crossorigin="anonymous"></script>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-DRM1ZRNLDN"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-DRM1ZRNLDN');
  </script>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Article",
  "headline": "Ruby でのシステムコール上のネストされたタイムアウトの問題",
  "author": {
    "@type": "Person",
    "address": "",
    "email": null,
    "identifier": "masyumaroking",
    "name": "masyumaroking"
  },
  "publisher": {
    "@type": "Person",
    "name": "masyumaroking"
  }
}
</script>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
  <header>
    <div class="container">
        <h1>Techioz Blog</h1>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Articles</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
    </div>
  </header>
  <main>
    <div class="container">
        <article>
                      <h2>Ruby
でのシステムコール上のネストされたタイムアウトの問題</h2>
                    <h2 id="概要">概要</h2>
                    <p>Ruby(on
                    Rails)のタイムアウトを使用しているときに、この奇妙な問題に遭遇しました。今回はタイムアウト</p>
                    <pre><code>timeout(10) do
 //some code involving http calls that takes more than 10 seconds
end
</code></pre>
                    <p>動かない。しかし、このタイムアウト</p>
                    <pre><code>timeout(20) do
 timeout(10) do
   //some code involving http calls that takes more than 10 seconds
 end
end
</code></pre>
                    <p>20秒後にタイムアウトします。システムコールが関係する場合、Ruby
                    のタイムアウトが適切に機能しないと読みました。その場合、ネストされたタイムアウトの数も機能しないはずです。なぜこれが
                    2 回目のタイムアウトでも機能するのでしょうか?</p>
                    <p>私が参照したリンク:
                    http://ph7spot.com/musings/system-timer</p>
                    <h2 id="解決策">解決策</h2>
                    <p>このようなことを行うには、タイムアウトとターミネータを組み合わせて使用するとうまくいくかもしれません。</p>
                    <p>タイムアウト メソッドの既知の欠点の 1
                    つは、タイムアウト
                    メソッドが常に厳密に適用されるわけではなく、多くの要因によってタイムアウトが妨げられる可能性があることです。</p>
        </article>
    </div>
  </main>
  <footer>
    <div class="container">
        <p>&copy; 2024 Techioz. All rights reserved.</p>
    </div>
  </footer>
</body>
</html>