<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <link rel="icon" href="../favicon.ico" />
  <link rel="stylesheet" href="../style.css">
  <title>Xero API に接続して請求書を作成しようとしていますが、次のエラーが発生します。 | Techioz</title>
  <style type="text/css">code{white-space: pre;}</style>
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1637770322917058"
     crossorigin="anonymous"></script>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-DRM1ZRNLDN"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-DRM1ZRNLDN');
  </script>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Article",
  "headline": "Xero API に接続して請求書を作成しようとしていますが、次のエラーが発生します。",
  "author": {
    "@type": "Person",
    "address": "",
    "email": null,
    "identifier": "masyumaroking",
    "name": "masyumaroking"
  },
  "publisher": {
    "@type": "Person",
    "name": "masyumaroking"
  }
}
</script>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
  <header>
    <div class="container">
        <h1>Techioz Blog</h1>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Articles</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
    </div>
  </header>
  <main>
    <div class="container">
        <article>
                      <h2>Xero API
に接続して請求書を作成しようとしていますが、次のエラーが発生します。</h2>
                    <h2 id="概要">概要</h2>
                    <p>Xero API
                    を使用して請求書を取得しようとすると、.get_invoices(’’).invoices
                    でエラーが発生します。</p>
                    <p>以下のエラーを参照してください。</p>
                    <pre><code>*** XeroRuby::ApiError Exception: Error message: the server returns an error

HTTP status code: 403

Response headers: {&quot;content-length&quot;=&gt;&quot;0&quot;, &quot;server&quot;=&gt;&quot;nginx&quot;, &quot;xero-correlation-id&quot;=&gt;&quot;c605f5e5-81e7-4763-ae07-093e7cb6f949&quot;, &quot;x-appminlimit-remaining&quot;=&gt;&quot;9998&quot;, &quot;expires&quot;=&gt;&quot;Thu, 02 Feb 2023 16:45:04 GMT&quot;, &quot;cache-control&quot;=&gt;&quot;max-age=0, no-cache, no-store&quot;, &quot;pragma&quot;=&gt;&quot;no-cache&quot;, &quot;date&quot;=&gt;&quot;Thu, 02 Feb 2023 16:45:04 GMT&quot;, &quot;connection&quot;=&gt;&quot;keep-alive&quot;, &quot;x-client-tls-ver&quot;=&gt;&quot;tls1.3&quot;}

Response body:

</code></pre>
                    <p>インデックスコントローラー</p>
                    <pre><code>
require &#39;xero-ruby&#39;

    creds = {
      client_id: &#39;...&#39;,
      client_secret: &#39;...&#39;,
      grant_type: &#39;client_credentials&#39;
    }

    xero_client = XeroRuby::ApiClient.new(credentials: creds)

    @token_set = xero_client.get_client_credentials_token

    byebug

    @invoices = xero_client.accounting_api.get_invoices(&#39;&#39;).invoices

</code></pre>
                    <h2 id="解決策">解決策</h2>
                    <p>お電話の際にテナント ID
                    をご確認いただけますか。あなたが言及した相関 ID の
                    Xero ログを見ると、テナント ID
                    は「page=1-100」として送信されています。</p>
        </article>
    </div>
  </main>
  <footer>
    <div class="container">
        <p>&copy; 2024 Techioz. All rights reserved.</p>
    </div>
  </footer>
</body>
</html>